'use strict';

import { NativeModules } from 'react-native';

/**
 * @hidden
 */
const NumberlyModule = NativeModules.NumberlyModule;

/**
 * Numberly's User Module
 *
 * @Warning You must always use the {@linkcode Numberly.user} instead of a new instance.
 */
export class NumberlyUser {
  /**
   * Get the unique installation ID, generated by Numberly.
   */
  public installationID(): Promise<string> {
    return NumberlyModule.userInstallationID();
  }
}
